# !! File must end with empty line !!
dependencies:
  # !! "alias: preview" must be last entry in dependencies array !!
  # !! Place custom dependencies above !!
- alias: preview
  name: spring-boot-http-gradle-jenkins-x
  repository: file://../spring-boot-http-gradle-jenkins-x
